# Generated by Django 5.2.3 on 2025-07-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discipline',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
