# Generated by Django 5.2.3 on 2025-07-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_remove_course_discipline_delete_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content_files/', verbose_name='Файл'),
        ),
    ]
