# Generated by Django 5.2.3 on 2026-03-06 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_userprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Суроо')),
            ],
        ),
        migrations.AddField(
            model_name='userprogress',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Тест упайы'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_data',
            field=models.TextField(blank=True, verbose_name='Маалымат / Шилтеме / Текст'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Сүрөт'), ('video', 'Видео'), ('file', 'Файл')], max_length=10, verbose_name='Контенттин түрү'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Тартиби'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн күнү'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Сүрөттөмө'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Курстун мукабасы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Курстун аталышы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн күнү'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Тартиби'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Сабактын аталышы'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Аяктады'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Вариант')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Туура жооп')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='front.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тесттин аталышы')),
                ('time_limit', models.PositiveIntegerField(default=5, verbose_name='Убакыт чектөөсү (мүнөт менен)')),
                ('pass_percentage', models.PositiveIntegerField(default=70, verbose_name='Өтүү упайы (%)')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='front.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='front.quiz'),
        ),
    ]
