# Generated by Django 6.0.3 on 2026-03-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_quizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
        migrations.AlterField(
            model_name='content',
            name='content_data',
            field=models.TextField(blank=True, null=True, verbose_name='Текст же Видео шилтемеси'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Сүрөт (Файл)'), ('video', 'Видео (YouTube шилтеме)'), ('video_file', 'Видео (MP4 Файл)'), ('file', 'Документ/Файл')], max_length=15, verbose_name='Контенттин түрү'),
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, help_text='Сүрөт, видео же документти тандаңыз', null=True, upload_to='lesson_contents/', verbose_name='Компьютерден жүктөө'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Тартиби (Порядковый номер)'),
        ),
    ]
