# Generated by Django 6.0.3 on 2026-03-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_alter_comment_options_alter_content_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Сабактын мазмуну', 'verbose_name_plural': 'Сабактын мазмундары'},
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_contents/', verbose_name='Компьютерден жүктөө'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Тартиби'),
        ),
    ]
