# Generated by Django 6.0.2 on 2026-03-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_quizsessionimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizsessionimage',
            options={'verbose_name': 'Прокторинг сүрөтү', 'verbose_name_plural': 'Прокторинг сүрөттөрү'},
        ),
    ]
